### ISSUE TITLE
Coloque os links assim....

### ISSUE THREAD

**Issue by glaucia86** [apsantos-dev/webinar-angular-team#1]
**[Extensions for the Visual Studio family of products](https://marketplace.visualstudio.com/?WT.mc_id=webinar-youtube-gllemos)**

**[Using Angular in Visual Studio Code](https://code.visualstudio.com/docs/nodejs/angular-tutorial?wt.mc_id=webinar-youtube-event-gllemos)**

**[Baixem o VsCode](http://bit.ly/vscode-webinar)**

**[Nova plataforma de Cursos Gratuitos da MS. Entrem agora e conheçam](http://bit.ly/ms-learning-gratuito)**

**Comment by apsantos-dev** [comment]
Top...

Vou alterar
